spring.application.name=spring-ai-demo
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID}

# Chat Options
# spring.ai.google.genai.chat.options.model=gemini-1.5-flash
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview



# The Magic Line for Speed!
# This enables Virtual Threads to handle thousands of AI calls.
spring.threads.virtual.enabled=true


# NEW: See the Advisor working in the terminal
logging.level.org.springframework.ai.chat.client.advisor=DEBUG


# Show your own Service logs
logging.level.com.cm.spring_ai_demo=DEBUG

# Show Spring AI's internal communication logs
logging.level.org.springframework.ai=DEBUG

# Optional: Color-coded logs for easier reading in terminal
spring.output.ansi.enabled=ALWAYS
